import AppKit
import Carbon.HIToolbox
import Combine

// MARK: - Pasteboard privacy marker types (nspasteboard.com convention)

enum PasteboardPrivacyTypes {
    static let concealed     = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transient     = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
}

// MARK: - Global hotkey key combination (in Carbon space)

struct KeyCombo: Equatable {
    var keyCode: UInt32
    var carbonModifiers: UInt32

    // Defaults are ⌥⇧ (Option+Shift) + a letter, grouped by function on the left of the keyboard for comfort:
    // E history · R record · D draw/annotate · F fast text (OCR) · O upload. ⌥⇧ is easy to hold and rarely an
    // app accelerator, so the global Carbon hotkey fires; ⌘⇧+letter is avoided (mined by VS Code/browsers).
    static let defaultCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_E), carbonModifiers: UInt32(optionKey | shiftKey))            // ⌥⇧E history
    static let defaultVoiceCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_R), carbonModifiers: UInt32(optionKey | shiftKey))       // ⌥⇧R record
    static let defaultCaptureCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_D), carbonModifiers: UInt32(optionKey | shiftKey))     // ⌥⇧D draw/annotate
    static let defaultTextCaptureCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_F), carbonModifiers: UInt32(optionKey | shiftKey)) // ⌥⇧F fast OCR
    static let defaultUploadCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_O), carbonModifiers: UInt32(optionKey | shiftKey))      // ⌥⇧O upload
    static let defaultMeetingCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_M), carbonModifiers: UInt32(optionKey | shiftKey))     // ⌥⇧M meeting
    static let defaultScreenRecCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_V), carbonModifiers: UInt32(optionKey | shiftKey))   // ⌥⇧V video (screen recording)
    static let defaultScrollCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_S), carbonModifiers: UInt32(optionKey | shiftKey))      // ⌥⇧S scrolling capture

    // Previous ⌥⌘ defaults and the brief ⌥⇧ Y/R/T/G/E set — migrate anyone still on them onto the new set.
    static let prevOptCmdPanel   = KeyCombo(keyCode: UInt32(kVK_ANSI_Y), carbonModifiers: UInt32(cmdKey | optionKey))
    static let prevOptCmdVoice   = KeyCombo(keyCode: UInt32(kVK_ANSI_R), carbonModifiers: UInt32(cmdKey | optionKey))
    static let prevOptCmdCapture = KeyCombo(keyCode: UInt32(kVK_ANSI_T), carbonModifiers: UInt32(cmdKey | optionKey))
    static let prevOptCmdUpload  = KeyCombo(keyCode: UInt32(kVK_ANSI_G), carbonModifiers: UInt32(cmdKey | optionKey))
    static let prevOptCmdText    = KeyCombo(keyCode: UInt32(kVK_ANSI_E), carbonModifiers: UInt32(cmdKey | optionKey))
    static let prevShiftPanel    = KeyCombo(keyCode: UInt32(kVK_ANSI_Y), carbonModifiers: UInt32(optionKey | shiftKey))
    static let prevShiftCapture  = KeyCombo(keyCode: UInt32(kVK_ANSI_T), carbonModifiers: UInt32(optionKey | shiftKey))
    static let prevShiftUpload   = KeyCombo(keyCode: UInt32(kVK_ANSI_G), carbonModifiers: UInt32(optionKey | shiftKey))
    static let prevShiftText     = KeyCombo(keyCode: UInt32(kVK_ANSI_E), carbonModifiers: UInt32(optionKey | shiftKey))

    // Older defaults, kept only to migrate anyone still on them onto the current set (see migration in init).
    static let legacyPanelCombo   = KeyCombo(keyCode: UInt32(kVK_ANSI_E), carbonModifiers: UInt32(cmdKey | shiftKey)) // ⌘⇧E
    static let legacyVoiceCombo   = KeyCombo(keyCode: UInt32(kVK_ANSI_I), carbonModifiers: UInt32(cmdKey | shiftKey)) // ⌘⇧I
    static let legacyCaptureUCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_U), carbonModifiers: UInt32(cmdKey | shiftKey)) // ⌘⇧U
    // Brief interim defaults (⌥⌘V panel, ⌥⌘S capture) shipped before Y/T — migrate those forward too.
    static let interimPanelCombo   = KeyCombo(keyCode: UInt32(kVK_ANSI_V), carbonModifiers: UInt32(cmdKey | optionKey)) // ⌥⌘V
    static let interimCaptureCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_S), carbonModifiers: UInt32(cmdKey | optionKey)) // ⌥⌘S
    /// Oldest capture default (⌘⇧2), still migrated forward.
    static let legacyCaptureCombo = KeyCombo(keyCode: UInt32(kVK_ANSI_2),
                                             carbonModifiers: UInt32(cmdKey | shiftKey))

    var isValid: Bool { carbonModifiers != 0 }

    var displayString: String {
        var s = ""
        if carbonModifiers & UInt32(controlKey) != 0 { s += "⌃" }
        if carbonModifiers & UInt32(optionKey)  != 0 { s += "⌥" }
        if carbonModifiers & UInt32(shiftKey)   != 0 { s += "⇧" }
        if carbonModifiers & UInt32(cmdKey)     != 0 { s += "⌘" }
        s += KeyCombo.keyName(for: keyCode)
        return s
    }

    /// NSMenuItem key equivalent for this combo — lets the status menu render the shortcut
    /// right-aligned in system gray like every native menu (instead of embedded in the title).
    /// Empty for keys with no single-character form (callers fall back to the title suffix).
    var menuKeyEquivalent: String {
        // keyName renders these as GLYPHS (↩ ⇥ ⎋ ⌫), each exactly one Character, so the `count == 1`
        // test below used to hand the glyph itself to NSMenuItem. The row LOOKED right — AppKit draws
        // whatever character it gets — but no keypress can match a glyph, so the equivalent was dead
        // and the title-suffix fallback never ran either. AppKit matches these keys by their control
        // characters. Reachable: ⌥↩ passes both isValid and the recorder's non-Shift-modifier rule.
        switch Int(keyCode) {
        case kVK_Space:  return " "
        case kVK_Return: return "\r"
        case kVK_Tab:    return "\t"
        case kVK_Escape: return "\u{1b}"
        case kVK_Delete: return "\u{8}"
        default: break
        }
        let name = KeyCombo.keyName(for: keyCode)
        return name.count == 1 ? name.lowercased() : ""
    }

    var cocoaModifiers: NSEvent.ModifierFlags {
        var f: NSEvent.ModifierFlags = []
        if carbonModifiers & UInt32(controlKey) != 0 { f.insert(.control) }
        if carbonModifiers & UInt32(optionKey)  != 0 { f.insert(.option) }
        if carbonModifiers & UInt32(shiftKey)   != 0 { f.insert(.shift) }
        if carbonModifiers & UInt32(cmdKey)     != 0 { f.insert(.command) }
        return f
    }

    static func keyName(for keyCode: UInt32) -> String {
        let map: [UInt32: String] = [
            UInt32(kVK_ANSI_A): "A", UInt32(kVK_ANSI_B): "B", UInt32(kVK_ANSI_C): "C",
            UInt32(kVK_ANSI_D): "D", UInt32(kVK_ANSI_E): "E", UInt32(kVK_ANSI_F): "F",
            UInt32(kVK_ANSI_G): "G", UInt32(kVK_ANSI_H): "H", UInt32(kVK_ANSI_I): "I",
            UInt32(kVK_ANSI_J): "J", UInt32(kVK_ANSI_K): "K", UInt32(kVK_ANSI_L): "L",
            UInt32(kVK_ANSI_M): "M", UInt32(kVK_ANSI_N): "N", UInt32(kVK_ANSI_O): "O",
            UInt32(kVK_ANSI_P): "P", UInt32(kVK_ANSI_Q): "Q", UInt32(kVK_ANSI_R): "R",
            UInt32(kVK_ANSI_S): "S", UInt32(kVK_ANSI_T): "T", UInt32(kVK_ANSI_U): "U",
            UInt32(kVK_ANSI_V): "V", UInt32(kVK_ANSI_W): "W", UInt32(kVK_ANSI_X): "X",
            UInt32(kVK_ANSI_Y): "Y", UInt32(kVK_ANSI_Z): "Z",
            UInt32(kVK_ANSI_0): "0", UInt32(kVK_ANSI_1): "1", UInt32(kVK_ANSI_2): "2",
            UInt32(kVK_ANSI_3): "3", UInt32(kVK_ANSI_4): "4", UInt32(kVK_ANSI_5): "5",
            UInt32(kVK_ANSI_6): "6", UInt32(kVK_ANSI_7): "7", UInt32(kVK_ANSI_8): "8",
            UInt32(kVK_ANSI_9): "9",
            UInt32(kVK_Space): "Space", UInt32(kVK_Return): "↩", UInt32(kVK_Tab): "⇥",
            UInt32(kVK_Escape): "⎋", UInt32(kVK_Delete): "⌫",
            UInt32(kVK_ANSI_Period): ".", UInt32(kVK_ANSI_Comma): ",",
            UInt32(kVK_ANSI_Slash): "/", UInt32(kVK_ANSI_Semicolon): ";"
        ]
        return map[keyCode] ?? String(format: "Key %02X", keyCode)
    }

    /// Suggested combinations to pick without recording (shown in Preferences), and the pool the startup
    /// recovery/dedup loops draw from when a shortcut cannot register. Mostly ⌥⇧ letters, which rarely
    /// collide with app accelerators (so the global hotkey reliably fires). Every entry MUST carry a
    /// modifier other than Shift — a bare or Shift-only combo registers fine and then swallows that key in
    /// every app on the Mac (see ShortcutTableTests). Must also stay pairwise distinct: the recovery loops
    /// walk this list in order, and Preferences renders it keyed by displayString.
    static let suggestions: [KeyCombo] = [
        KeyCombo(keyCode: UInt32(kVK_ANSI_Y), carbonModifiers: UInt32(optionKey | shiftKey)),  // ⌥⇧Y (panel)
        KeyCombo(keyCode: UInt32(kVK_ANSI_R), carbonModifiers: UInt32(optionKey | shiftKey)),  // ⌥⇧R (voice)
        KeyCombo(keyCode: UInt32(kVK_ANSI_T), carbonModifiers: UInt32(optionKey | shiftKey)),  // ⌥⇧T (capture)
        KeyCombo(keyCode: UInt32(kVK_ANSI_G), carbonModifiers: UInt32(optionKey | shiftKey)),  // ⌥⇧G
        KeyCombo(keyCode: UInt32(kVK_ANSI_K), carbonModifiers: UInt32(optionKey | shiftKey)),  // ⌥⇧K
        KeyCombo(keyCode: UInt32(kVK_ANSI_J), carbonModifiers: UInt32(optionKey | shiftKey)),  // ⌥⇧J
        KeyCombo(keyCode: UInt32(kVK_Space),  carbonModifiers: UInt32(optionKey)),           // ⌥Space
        KeyCombo(keyCode: UInt32(kVK_ANSI_M), carbonModifiers: UInt32(cmdKey | shiftKey))    // ⌘⇧M
    ]
}

func cocoaToCarbonModifiers(_ flags: NSEvent.ModifierFlags) -> UInt32 {
    var carbon: UInt32 = 0
    if flags.contains(.command) { carbon |= UInt32(cmdKey) }
    if flags.contains(.shift)   { carbon |= UInt32(shiftKey) }
    if flags.contains(.option)  { carbon |= UInt32(optionKey) }
    if flags.contains(.control) { carbon |= UInt32(controlKey) }
    return carbon
}

// MARK: - Settings store (UserDefaults), single source of truth

final class Settings: ObservableObject {
    static let shared = Settings()
    private let d = UserDefaults.standard

    /// First-run onboarding flag (see WelcomeView). Plain UserDefaults — no need to publish it.
    var hasSeenWelcome: Bool {
        get { d.bool(forKey: "hasSeenWelcome") }
        set { d.set(newValue, forKey: "hasSeenWelcome") }
    }

    private enum K {
        static let maxItems   = "maxItems"
        static let keyCode    = "hotKeyCode"
        static let mods       = "hotKeyModifiers"
        static let autoPaste  = "autoPaste"
        static let sounds     = "soundEffects"
        static let concealed  = "privacy.ignoreConcealed"
        static let transient  = "privacy.ignoreTransient"
        static let autoGen    = "privacy.ignoreAutoGenerated"
        static let excluded   = "privacy.excludedBundleIDs"
        static let captureSrc = "captureSource"
        static let cleanCap   = "cleanCapture"
        static let capDest    = "captureDestination"
        static let detectRem  = "detectRemoteSource"
        static let transLang  = "transcriptionLanguage"
        static let transVocab = "transcriptionVocabulary"
        static let localModel = "localModel"
        static let keyCode2   = "voiceHotKeyCode"
        static let mods2      = "voiceHotKeyModifiers"
        static let keyCode3   = "captureHotKeyCode"
        static let mods3      = "captureHotKeyModifiers"
        static let keyCode4   = "uploadHotKeyCode"
        static let mods4      = "uploadHotKeyModifiers"
        static let keyCode5   = "textCaptureHotKeyCode"
        static let mods5      = "textCaptureHotKeyModifiers"
        static let keyCode6   = "meetingHotKeyCode"
        static let mods6      = "meetingHotKeyModifiers"
        static let keyCode7   = "screenRecHotKeyCode"
        static let mods7      = "screenRecHotKeyModifiers"
        static let keyCode8   = "scrollCaptureHotKeyCode"
        static let mods8      = "scrollCaptureHotKeyModifiers"
        static let uiLang     = "uiLanguage"
    }

    @Published var maxItems: Int          { didSet { d.set(maxItems, forKey: K.maxItems) } }
    @Published var combo: KeyCombo        { didSet {
        d.set(Int(combo.keyCode), forKey: K.keyCode)
        d.set(Int(combo.carbonModifiers), forKey: K.mods)
    } }
    @Published var autoPaste: Bool        { didSet { d.set(autoPaste, forKey: K.autoPaste) } }
    /// Interface sound effects (copy tick, capture pop, record cues…). See SoundFX.
    @Published var soundEffects: Bool     { didSet { d.set(soundEffects, forKey: K.sounds) } }
    @Published var ignoreConcealed: Bool  { didSet { d.set(ignoreConcealed, forKey: K.concealed) } }
    @Published var ignoreTransient: Bool  { didSet { d.set(ignoreTransient, forKey: K.transient) } }
    @Published var ignoreAutoGenerated: Bool { didSet { d.set(ignoreAutoGenerated, forKey: K.autoGen) } }
    @Published var excludedBundleIDs: [String] { didSet { d.set(excludedBundleIDs, forKey: K.excluded) } }
    @Published var captureSource: Bool    { didSet { d.set(captureSource, forKey: K.captureSrc) } }
    /// "Always paste clean": store rich copies as clean Markdown (keeps bold/italic + emojis, drops styling).
    @Published var cleanCapture: Bool     { didSet { d.set(cleanCapture, forKey: K.cleanCap) } }
    /// Where a region capture lands: "editor" (annotate first, default) or "clipboard" (straight to
    /// history + clipboard, no editor).
    @Published var captureDestination: String { didSet { d.set(captureDestination, forKey: K.capDest) } }
    @Published var detectRemoteSource: Bool { didSet { d.set(detectRemoteSource, forKey: K.detectRem) } }
    @Published var transcriptionLanguage: String { didSet { d.set(transcriptionLanguage, forKey: K.transLang) } }
    /// Context words / vocabulary (names, brands, jargon) sent to the transcriber so it spells them right.
    @Published var transcriptionVocabulary: String { didSet { d.set(transcriptionVocabulary, forKey: K.transVocab) } }
    /// On-device (WhisperKit) transcription model name.
    @Published var localModel: String { didSet { d.set(localModel, forKey: K.localModel) } }
    @Published var voiceCombo: KeyCombo   { didSet {
        d.set(Int(voiceCombo.keyCode), forKey: K.keyCode2)
        d.set(Int(voiceCombo.carbonModifiers), forKey: K.mods2)
    } }
    @Published var captureCombo: KeyCombo { didSet {
        d.set(Int(captureCombo.keyCode), forKey: K.keyCode3)
        d.set(Int(captureCombo.carbonModifiers), forKey: K.mods3)
    } }
    /// Global shortcut to open the "Upload audio to transcribe" window.
    @Published var uploadCombo: KeyCombo  { didSet {
        d.set(Int(uploadCombo.keyCode), forKey: K.keyCode4)
        d.set(Int(uploadCombo.carbonModifiers), forKey: K.mods4)
    } }
    /// Global shortcut to capture a region and extract its text straight to the clipboard (OCR, no editor).
    @Published var textCaptureCombo: KeyCombo { didSet {
        d.set(Int(textCaptureCombo.keyCode), forKey: K.keyCode5)
        d.set(Int(textCaptureCombo.carbonModifiers), forKey: K.mods5)
    } }
    /// Global shortcut to start/stop a meeting recording (mic + system audio).
    @Published var meetingCombo: KeyCombo { didSet {
        d.set(Int(meetingCombo.keyCode), forKey: K.keyCode6)
        d.set(Int(meetingCombo.carbonModifiers), forKey: K.mods6)
    } }
    /// Global shortcut to start/stop a screen recording (region → video/GIF).
    @Published var screenRecCombo: KeyCombo { didSet {
        d.set(Int(screenRecCombo.keyCode), forKey: K.keyCode7)
        d.set(Int(screenRecCombo.carbonModifiers), forKey: K.mods7)
    } }
    /// Global shortcut for a scrolling capture (long page → one stitched image).
    @Published var scrollCombo: KeyCombo { didSet {
        d.set(Int(scrollCombo.keyCode), forKey: K.keyCode8)
        d.set(Int(scrollCombo.carbonModifiers), forKey: K.mods8)
    } }
    @Published var uiLanguage: String     { didSet {
        d.set(uiLanguage, forKey: K.uiLang)
        // Keep the audio language following the platform language, but ONLY while the user hasn't
        // deliberately diverged: sync only if it was still tracking the previous UI language. This never
        // overwrites an explicit choice (including "" = auto-detect).
        if uiLanguage != oldValue, transcriptionLanguage == oldValue { transcriptionLanguage = uiLanguage }
    } }

    /// Simple toggle that controls all three privacy filters at once.
    var ignoreSensitive: Bool {
        get { ignoreConcealed || ignoreTransient || ignoreAutoGenerated }
        set { ignoreConcealed = newValue; ignoreTransient = newValue; ignoreAutoGenerated = newValue }
    }

    private init() {
        Settings.migratePreviousBundleDomainIfNeeded()   // must precede everything that reads a default
        Settings.migrateLegacyDefaultsIfNeeded()
        d.register(defaults: [
            // Registration domain only: init assigns `maxItems` WITHOUT firing didSet (Swift skips property
            // observers during initialization), so nothing is written to the persistent domain until the user
            // moves the stepper. Raising this therefore reaches everyone who never chose a value — including
            // existing installs — while a deliberate 200 stays 200 (it lives in the persistent domain).
            K.maxItems: 500,
            K.keyCode: Int(kVK_ANSI_E),
            K.mods: Int(optionKey | shiftKey),
            K.autoPaste: true,
            K.sounds: true,
            K.concealed: true,
            K.transient: true,
            K.autoGen: true,
            K.captureSrc: true,
            K.cleanCap: true,
            K.capDest: "editor",
            K.detectRem: true,
            K.transLang: "",   // auto-detect: forcing a language mistranscribes any other (UI defaults to en, so "es" was wrong on fresh installs; local installs seed their own via install.sh)
            K.transVocab: "",
            K.localModel: "small",   // best accuracy/speed balance on Apple Silicon (downloads ~480 MB once)
            K.keyCode2: Int(kVK_ANSI_R),
            K.mods2: Int(optionKey | shiftKey),
            K.keyCode3: Int(kVK_ANSI_D),
            K.mods3: Int(optionKey | shiftKey),
            K.keyCode4: Int(kVK_ANSI_O),
            K.mods4: Int(optionKey | shiftKey),
            K.keyCode5: Int(kVK_ANSI_F),
            K.mods5: Int(optionKey | shiftKey),
            K.keyCode6: Int(kVK_ANSI_M),
            K.mods6: Int(optionKey | shiftKey),
            K.keyCode7: Int(kVK_ANSI_V),
            K.mods7: Int(optionKey | shiftKey),
            K.keyCode8: Int(kVK_ANSI_S),
            K.mods8: Int(optionKey | shiftKey),
            K.uiLang: "en"   // English is the base/default UI language (open-source collaboration)
        ])
        maxItems = d.integer(forKey: K.maxItems)
        combo = KeyCombo(keyCode: UInt32(d.integer(forKey: K.keyCode)),
                         carbonModifiers: UInt32(d.integer(forKey: K.mods)))
        autoPaste = d.object(forKey: K.autoPaste) as? Bool ?? true
        soundEffects = d.object(forKey: K.sounds) as? Bool ?? true
        ignoreConcealed = d.object(forKey: K.concealed) as? Bool ?? true
        ignoreTransient = d.object(forKey: K.transient) as? Bool ?? true
        ignoreAutoGenerated = d.object(forKey: K.autoGen) as? Bool ?? true
        excludedBundleIDs = d.stringArray(forKey: K.excluded) ?? []
        captureSource = d.object(forKey: K.captureSrc) as? Bool ?? true
        cleanCapture = d.object(forKey: K.cleanCap) as? Bool ?? true
        captureDestination = d.string(forKey: K.capDest) ?? "editor"
        detectRemoteSource = d.object(forKey: K.detectRem) as? Bool ?? true
        transcriptionLanguage = d.string(forKey: K.transLang) ?? "es"
        transcriptionVocabulary = d.string(forKey: K.transVocab) ?? ""
        localModel = d.string(forKey: K.localModel) ?? "small"
        voiceCombo = KeyCombo(keyCode: UInt32(d.integer(forKey: K.keyCode2)),
                              carbonModifiers: UInt32(d.integer(forKey: K.mods2)))
        captureCombo = KeyCombo(keyCode: UInt32(d.integer(forKey: K.keyCode3)),
                                carbonModifiers: UInt32(d.integer(forKey: K.mods3)))
        uploadCombo = KeyCombo(keyCode: UInt32(d.integer(forKey: K.keyCode4)),
                               carbonModifiers: UInt32(d.integer(forKey: K.mods4)))
        textCaptureCombo = KeyCombo(keyCode: UInt32(d.integer(forKey: K.keyCode5)),
                                    carbonModifiers: UInt32(d.integer(forKey: K.mods5)))
        meetingCombo = KeyCombo(keyCode: UInt32(d.integer(forKey: K.keyCode6)),
                                carbonModifiers: UInt32(d.integer(forKey: K.mods6)))
        screenRecCombo = KeyCombo(keyCode: UInt32(d.integer(forKey: K.keyCode7)),
                                  carbonModifiers: UInt32(d.integer(forKey: K.mods7)))
        scrollCombo = KeyCombo(keyCode: UInt32(d.integer(forKey: K.keyCode8)),
                               carbonModifiers: UInt32(d.integer(forKey: K.mods8)))
        uiLanguage = d.string(forKey: K.uiLang) ?? "en"

        // One-time migration: the capture default changed from ⌘⇧2 to ⌘⇧U (⌘⇧2 was hijacked by apps like Loom).
        // For anyone still on the old persisted ⌘⇧2, move them to ⌘⇧U. If the user chose another shortcut, keep it.
        let migCaptureKey = "migratedCaptureToU"
        if !d.bool(forKey: migCaptureKey) {
            if captureCombo == KeyCombo.legacyCaptureCombo { captureCombo = KeyCombo.legacyCaptureUCombo }
            d.set(true, forKey: migCaptureKey)
        }

        // One-time migration of the default shortcuts onto the current ⌥⌘ set with uncommon letters
        // (panel ⌥⌘Y · voice ⌥⌘R · capture ⌥⌘T). Catches BOTH the original ⌘⇧E/⌘⇧I/⌘⇧U defaults and the
        // brief interim ⌥⌘V/⌥⌘S defaults. Anyone who picked their own combo keeps it. Uses a fresh flag (V3)
        // so users who already ran the interim build still advance. Must run AFTER migratedCaptureToU so a
        // ⌘⇧2 capture default reaches ⌘⇧U here and then advances to ⌥⌘T.
        let migHotkeysV3 = "migratedHotkeysV3"
        if !d.bool(forKey: migHotkeysV3) {
            if combo == KeyCombo.legacyPanelCombo || combo == KeyCombo.interimPanelCombo { combo = KeyCombo.defaultCombo }
            if voiceCombo == KeyCombo.legacyVoiceCombo { voiceCombo = KeyCombo.defaultVoiceCombo }
            if captureCombo == KeyCombo.legacyCaptureUCombo || captureCombo == KeyCombo.interimCaptureCombo { captureCombo = KeyCombo.defaultCaptureCombo }
            d.set(true, forKey: migHotkeysV3)
        }

        // One-time migration from the ⌥⌘ defaults to the new ⌥⇧ set (⌥⌘ was awkward to press). Anyone still
        // on an ⌥⌘ default moves over; a custom combo is kept.
        let migHotkeysV4 = "migratedHotkeysV4"
        if !d.bool(forKey: migHotkeysV4) {
            if combo == KeyCombo.prevOptCmdPanel { combo = KeyCombo.defaultCombo }
            if voiceCombo == KeyCombo.prevOptCmdVoice { voiceCombo = KeyCombo.defaultVoiceCombo }
            if captureCombo == KeyCombo.prevOptCmdCapture { captureCombo = KeyCombo.defaultCaptureCombo }
            if uploadCombo == KeyCombo.prevOptCmdUpload { uploadCombo = KeyCombo.defaultUploadCombo }
            if textCaptureCombo == KeyCombo.prevOptCmdText { textCaptureCombo = KeyCombo.defaultTextCaptureCombo }
            d.set(true, forKey: migHotkeysV4)
        }

        // Reletter migration: the brief ⌥⇧ Y/T/G/E set → the function-grouped E/R/D/F/O set (voice ⌥⇧R kept).
        let migHotkeysV5 = "migratedHotkeysV5"
        if !d.bool(forKey: migHotkeysV5) {
            if combo == KeyCombo.prevShiftPanel { combo = KeyCombo.defaultCombo }                       // ⌥⇧Y → ⌥⇧E
            if captureCombo == KeyCombo.prevShiftCapture { captureCombo = KeyCombo.defaultCaptureCombo } // ⌥⇧T → ⌥⇧D
            if uploadCombo == KeyCombo.prevShiftUpload { uploadCombo = KeyCombo.defaultUploadCombo }     // ⌥⇧G → ⌥⇧O
            if textCaptureCombo == KeyCombo.prevShiftText { textCaptureCombo = KeyCombo.defaultTextCaptureCombo } // ⌥⇧E → ⌥⇧F
            d.set(true, forKey: migHotkeysV5)
        }

        // The annotation editor's default tool changed from arrow to pencil. It persists the tool on
        // EVERY open, so the old default had already written "arrow" for anyone who opened the editor
        // once — indistinguishable from a deliberate choice, and it would pin them to the old default
        // forever. Clear that one value so the new default applies; any other stored tool is a real
        // preference and is left alone.
        let migEditorTool = "migratedEditorToolV2"
        if !d.bool(forKey: migEditorTool) {
            if d.string(forKey: "klip.editor.tool") == "arrow" { d.removeObject(forKey: "klip.editor.tool") }
            d.set(true, forKey: migEditorTool)
        }
    }

    func addExcludedApp(_ id: String) {
        guard !id.isEmpty, !excludedBundleIDs.contains(id) else { return }
        excludedBundleIDs.append(id)
    }

    func removeExcludedApp(_ id: String) {
        excludedBundleIDs.removeAll { $0 == id }
    }

    // MARK: - Migration from the old domains

    /// The bundle id changed, and UserDefaults.standard is the BUNDLE's domain — so on the first launch
    /// after the rename every setting reads as unset: shortcuts back to defaults, language back to the
    /// system one, the welcome window again, and every one-time migration flag cleared so the hotkey
    /// migrations would re-run and remap combos the user had chosen. Copy the whole old domain across.
    /// Whole-dictionary rather than a key list: the flags matter as much as the values, and a list here
    /// would go stale the next time a setting is added.
    private static let migratedDomainKey = "migratedFromProperDomain"

    private static func migratePreviousBundleDomainIfNeeded() {
        // Only when we ARE Klip. UserDefaults.standard is whatever the HOST process's domain is, so
        // without this the copy also fires inside the test runner and hands it the user's real
        // settings — which is exactly how the localization suite caught this.
        guard Bundle.main.bundleIdentifier == "io.github.tamibot.klip" else { return }
        let std = UserDefaults.standard
        guard !std.bool(forKey: migratedDomainKey) else { return }
        defer { std.set(true, forKey: migratedDomainKey) }
        guard let old = UserDefaults(suiteName: "com.proper.klip") else { return }
        for (key, value) in old.persistentDomain(forName: "com.proper.klip") ?? [:]
        where std.object(forKey: key) == nil {
            std.set(value, forKey: key)
        }
    }

    // MARK: - Migration from the old domain (Pasta → Klip)

    /// The suite name is the OLD app's, so it stays exactly as it was written on disk — renaming the
    /// string here would not rename anything, it would just stop finding those users' settings.
    private static let migratedFlagKey = "migratedFromPastaClip"

    private static func migrateLegacyDefaultsIfNeeded() {
        let std = UserDefaults.standard
        guard !std.bool(forKey: migratedFlagKey) else { return }
        defer { std.set(true, forKey: migratedFlagKey) }
        guard let legacy = UserDefaults(suiteName: "com.proper.pastaclip") else { return }
        // We don't migrate the shortcuts (Klip has its own defaults — the ⌥⇧ set above; ⌘⇧E / ⌘⇧I / ⌘⇧U
        // have been LEGACY combos since the V3 migration) or didAutoEnableLogin
        // (Klip registers itself under its new identity).
        let keys = [K.maxItems, K.autoPaste, K.concealed, K.transient, K.autoGen, K.excluded]
        for key in keys {
            if let value = legacy.object(forKey: key), std.object(forKey: key) == nil {
                std.set(value, forKey: key)
            }
        }
    }
}

/// Audio/dictation languages offered to the transcriber (endonyms), shared by Preferences and the Upload
/// window. "" (auto-detect) is added at the UI layer via the "lang.auto" string.
enum DictationLanguage {
    static let all: [(code: String, name: String)] = [
        ("en", "English"), ("es", "Español"), ("fr", "Français"), ("de", "Deutsch"),
        ("it", "Italiano"), ("pt", "Português"), ("zh", "中文"), ("ja", "日本語"),
        ("ko", "한국어"), ("ru", "Русский"), ("nl", "Nederlands"), ("hi", "हिन्दी")
    ]
}
